### PR TITLE
add minimal SLES support

### PR DESCRIPTION
**Pull request by costela**
If this module's still in minimal maintenance mode, these changes are enough to make it at least install and on SLES. :)

### CODE REVIEW

**Comment by karmi** [comment]
Hi @costela, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/puppet-logstashforwarder/pull/76.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by costela** [comment]
@karmi Wow, that was a nice coincidence. I thought this module had been abandoned and decided to close the PR on the same minute you commented. If the module's still on life-support, then I'll just repush the commits with a different email, but otherwise we can just let it drop.

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by costela** [comment]
Since logstash-forwarder has long been deprecated, there's probably no gain in leaving this PR open.

**Pull request closed without merging**
